#!/usr/bin/with-contenv bash
set -e

tar \
      --strip-components=1 \
      --exclude=zenphoto-${ZENPHOTO_VERSION}/README.md \
      --exclude=zenphoto-${ZENPHOTO_VERSION}/SECURITY.md \
      --exclude=zenphoto-${ZENPHOTO_VERSION}/SUPPORT.md \
      --exclude=zenphoto-${ZENPHOTO_VERSION}/LICENSE \
      --exclude=zenphoto-${ZENPHOTO_VERSION}/contributing.md \
      --exclude=zenphoto-${ZENPHOTO_VERSION}/albums \
      --exclude=zenphoto-${ZENPHOTO_VERSION}/backup \
      --exclude=zenphoto-${ZENPHOTO_VERSION}/cache \
      --exclude=zenphoto-${ZENPHOTO_VERSION}/cache_html \
      --exclude=zenphoto-${ZENPHOTO_VERSION}/uploaded \
      --exclude=zenphoto-${ZENPHOTO_VERSION}/plugins \
      --exclude=zenphoto-${ZENPHOTO_VERSION}/zp-data \
      --exclude=zenphoto-${ZENPHOTO_VERSION}/.git* \
      --gzip \
      --extract \
      --file /usr/local/src/zenphoto.tar.gz

mkdir -p /var/www/html/{albums,backup,cache,cache_html,uploaded,plugins,zp-data}

cp /var/www/html/zp-core/htaccess /var/www/html/.htaccess 
cp /var/www/html/zp-core/example_robots.txt /var/www/html/robots.txt

sed -i s/\\/zenphoto//g /var/www/html/robots.txt
